export interface RequestBody {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  data: any;
}

export enum ERRORS {
  UNKNOWN = "UNKNOWN",
  UNAUTHORIZED = "UNAUTHORIZED",
  PERMISSION_DENIED = "PERMISSION_DENIED",
  NO_SUCH_ENTITY = "NO_SUCH_ENTITY",
  AUTHORIZATION_FAILED = "AUTHORIZATION_FAILED",
  REQUEST_TIMEOUT = "REQUEST_TIMEOUT",
  EXISTED_DEPENDENCY = "EXISTED_DEPENDENCY",
  FAILED_DEPENDENCY = "FAILED_DEPENDENCY",
  RECURSION_FORBIDDEN = "RECURSION_FORBIDDEN",
  MAX_NESTING_REACHED = "MAX_NESTING_REACHED",
  DUPLICATE_ENTRY = "DUPLICATE_ENTRY",
  DEACTIVATED = "DEACTIVATED",
  NOT_VERIFIED = "NOT_VERIFIED",
  VALIDATION_FAILED = "VALIDATION_FAILED",
}

export const HTTP_CODES = {
  UNKNOWN: 500,
  UNAUTHORIZED: 401,
  PERMISSION_DENIED: 404,
  NO_SUCH_ENTITY: 404,
  AUTHORIZATION_FAILED: 401,
  REQUEST_TIMEOUT: 408,
  EXISTED_DEPENDENCY: 424,
  FAILED_DEPENDENCY: 424,
  RECURSION_FORBIDDEN: 404,
  MAX_NESTING_REACHED: 404,
  DUPLICATE_ENTRY: 500,
  DEACTIVATED: 404,
  NOT_VERIFIED: 404,
  VALIDATION_FAILED: 403,
} as { [key: string]: number };

export enum WeekDays {
  "Sunday" = "Sunday",
  "Monday" = "Monday",
  "Tuesday" = "Tuesday",
  "Wednesday" = "Wednesday",
  "Thursday" = "Thursday",
  "Friday" = "Friday",
  "Saturday" = "Saturday",
}
